---
- name: Verify Ansible version requirements
  assert:
    that: "ansible_version.full is version_compare('2.4', '>=')"
    msg: "You must update Ansible to at least v2.4 to use this playbook !"

- name: disable firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  become: true
  when: ansible_os_family == 'RedHat'
  tags: system

- name: install screen, jq and telnet on Debian family from repo
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - screen
    - telnet
    - jq
  become: true
  when: ansible_os_family == 'Debian' and not force_local_installation
  tags: system

- name: install screen, jq and telnet on Red Hat family from repo
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - screen
    - telnet
    - epel-release
    - jq
  become: true
  when: ansible_os_family == 'RedHat' and not force_local_installation
  tags: system

## Doesn't work for Debian on Ansible 2.5
#- name: install screen, jq and telnet from local
#  package:
#
## Doesn't work for Debian on Ansible 2.5    pkg: "{{ item }}"
#    state: present
#  with_items: "{% if ansible_os_family == 'Debian' %}{{ lookup('fileglob', '../../../files/*.deb').split(',') | sort }}
#    {% else %}{{ lookup('fileglob', '../../../files/*.rpm').split(',') | sort }}{% endif %}"
#  become: true
#  when: force_local_installation
#  tags: system

- name: install screen, jq and telnet on Debian from local
  apt:
    deb: "{{ item }}"
  with_items: "{{ lookup('fileglob', '../../../files/Debian/*_amd64.deb').split(',') | sort }}"
  become: true
  when: ansible_os_family == 'Debian' and force_local_installation
  tags: system
## In case of failure of previous steps
## Go https://stackoverflow.com/questions/30451939/cant-install-libc6-package

- name: install screen, jq and telnet on Red Hat from local
  package:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ lookup('fileglob', '../../../files/RedHat/*.rpm').split(',') | sort }}"
  become: true
  when: ansible_os_family == 'RedHat' and force_local_installation
  tags: system

- name: disable selinux at runtime
  shell: setenforce 0
  become: true
  when: ansible_os_family == 'RedHat' and ansible_selinux.status != 'disabled'
  tags: system

- name: disable selinux permanently
  selinux:
    state: disabled
  become: true
  when: ansible_os_family == 'RedHat' and ansible_selinux is defined and ansible_selinux != False
  tags: system
